In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Reading the dataset

In [2]:
df = pd.read_csv(r"C:\Users\hp\MyPractice\Froud Detection\Fraud.csv")

# First five rows

In [3]:
df.head(3)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0


# Info about the dataset

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype  
---  ------          -----  
 0   step            int64  
 1   type            object 
 2   amount          float64
 3   nameOrig        object 
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object 
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64  
 10  isFlaggedFraud  int64  
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB


In [5]:
df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
6362615,743,CASH_OUT,339682.13,C786484425,339682.13,0.0,C776919290,0.00,339682.13,1,0
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.0,C1881841831,0.00,0.00,1,0
6362617,743,CASH_OUT,6311409.28,C1162922333,6311409.28,0.0,C1365125890,68488.84,6379898.11,1,0
6362618,743,TRANSFER,850002.52,C1685995037,850002.52,0.0,C2080388513,0.00,0.00,1,0
6362619,743,CASH_OUT,850002.52,C1280323807,850002.52,0.0,C873221189,6510099.11,7360101.63,1,0


# Size of dataset

In [6]:
df.shape

(6362620, 11)

# Checking frequency of values in each categorical columns

In [7]:
df['type'].value_counts()

CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: type, dtype: int64

In [8]:
df['isFlaggedFraud'].value_counts()

0    6362604
1         16
Name: isFlaggedFraud, dtype: int64

In [9]:
df['isFraud'].value_counts()

0    6354407
1       8213
Name: isFraud, dtype: int64

In [10]:
df[(df['type']=='TRANSFER') | (df['type']=='PAYMENT')]['isFraud'].value_counts()

0    2680307
1       4097
Name: isFraud, dtype: int64

# Removing isFlaggedFraud Column

In [11]:
df=df.drop('isFlaggedFraud', axis=1)

In [12]:
df['isFraud'].value_counts()

0    6354407
1       8213
Name: isFraud, dtype: int64

# Dropping all rows from dataset where type column contains either 'CASH_OUT' or "CASH_IN" or 'DEBIT'

In [13]:
df = df[df['type'].isin(['TRANSFER', 'PAYMENT'])]

In [14]:
df.shape

(2684404, 10)

# Duplicate Rows

In [15]:
df[df.duplicated()]

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud


# Checking any null value in the dataset

In [16]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
dtype: int64

In [17]:
df

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.0,0.0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.0,0.0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.0,0.0,1
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.0,0.0,0
5,1,PAYMENT,7817.71,C90045638,53860.00,46042.29,M573487274,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...
6362610,742,TRANSFER,63416.99,C778071008,63416.99,0.00,C1812552860,0.0,0.0,1
6362612,743,TRANSFER,1258818.82,C1531301470,1258818.82,0.00,C1470998563,0.0,0.0,1
6362614,743,TRANSFER,339682.13,C2013999242,339682.13,0.00,C1850423904,0.0,0.0,1
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.00,C1881841831,0.0,0.0,1


# Feature Engineering : # Creating New Feature - 1. Transaction Time Feature

In [18]:
df['hour'] = df['step'] % 24
df['is_night'] = df['hour'].apply(lambda x : 1 if x < 6 else 0)

In [19]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,hour,is_night
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,1,1
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,1,1
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,1,1
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,1,1
5,1,PAYMENT,7817.71,C90045638,53860.0,46042.29,M573487274,0.0,0.0,0,1,1


# 2. Transaction Amount Feature

In [20]:
df['amount_ratio'] = df['amount']/(df['oldbalanceOrg'] + 1)

In [21]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,hour,is_night,amount_ratio
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,1,1,0.057834
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,1,1,0.087731
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,1,1,0.994505
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,1,1,0.280788
5,1,PAYMENT,7817.71,C90045638,53860.0,46042.29,M573487274,0.0,0.0,0,1,1,0.145146


# 3. Balance Difference Feature

In [22]:
df['sender_balance_change'] = df['oldbalanceOrg'] - df['newbalanceOrig']
df['receiver_balance_change'] = df['newbalanceDest'] - df['oldbalanceDest']

In [23]:
df[df['isFraud']==1]

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,hour,is_night,amount_ratio,sender_balance_change,receiver_balance_change
2,1,TRANSFER,181.00,C1305486145,181.00,0.0,C553264065,0.0,0.0,1,1,1,0.994505,181.00,0.0
251,1,TRANSFER,2806.00,C1420196421,2806.00,0.0,C972765878,0.0,0.0,1,1,1,0.999644,2806.00,0.0
680,1,TRANSFER,20128.00,C137533655,20128.00,0.0,C1848415041,0.0,0.0,1,1,1,0.999950,20128.00,0.0
969,1,TRANSFER,1277212.77,C1334405552,1277212.77,0.0,C431687661,0.0,0.0,1,1,1,0.999999,1277212.77,0.0
1115,1,TRANSFER,35063.63,C1364127192,35063.63,0.0,C1136419747,0.0,0.0,1,1,1,0.999971,35063.63,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6362610,742,TRANSFER,63416.99,C778071008,63416.99,0.0,C1812552860,0.0,0.0,1,22,0,0.999984,63416.99,0.0
6362612,743,TRANSFER,1258818.82,C1531301470,1258818.82,0.0,C1470998563,0.0,0.0,1,23,0,0.999999,1258818.82,0.0
6362614,743,TRANSFER,339682.13,C2013999242,339682.13,0.0,C1850423904,0.0,0.0,1,23,0,0.999997,339682.13,0.0
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.0,C1881841831,0.0,0.0,1,23,0,1.000000,6311409.28,0.0


# 4. Unexpected Zero Balance

In [24]:
df['orig_balance_zero'] = (df['oldbalanceOrg'] == 0).astype(int)
df['dest_balance_zero'] = (df['oldbalanceDest'] == 0).astype(int)

In [25]:
df.sample(4)

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,hour,is_night,amount_ratio,sender_balance_change,receiver_balance_change,orig_balance_zero,dest_balance_zero
3268119,251,TRANSFER,1224609.13,C1779531090,0.0,0.0,C2013573935,4387726.68,5612335.81,0,11,0,1.224609e+06,0.0,1224609.13,1,0
1808594,163,TRANSFER,207184.50,C1824019335,102028.0,0.0,C1381356862,16459.00,223643.50,0,19,0,2.030643e+00,102028.0,207184.50,0,0
831487,41,PAYMENT,21057.19,C1770574445,0.0,0.0,M2134110012,0.00,0.00,0,17,0,2.105719e+04,0.0,0.00,1,1
4144852,303,TRANSFER,382194.83,C1511145764,15196.0,0.0,C1398491573,1383470.87,1765665.70,0,15,0,2.514936e+01,15196.0,382194.83,0,0


In [26]:
df[df['isFraud'] == 1]

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,hour,is_night,amount_ratio,sender_balance_change,receiver_balance_change,orig_balance_zero,dest_balance_zero
2,1,TRANSFER,181.00,C1305486145,181.00,0.0,C553264065,0.0,0.0,1,1,1,0.994505,181.00,0.0,0,1
251,1,TRANSFER,2806.00,C1420196421,2806.00,0.0,C972765878,0.0,0.0,1,1,1,0.999644,2806.00,0.0,0,1
680,1,TRANSFER,20128.00,C137533655,20128.00,0.0,C1848415041,0.0,0.0,1,1,1,0.999950,20128.00,0.0,0,1
969,1,TRANSFER,1277212.77,C1334405552,1277212.77,0.0,C431687661,0.0,0.0,1,1,1,0.999999,1277212.77,0.0,0,1
1115,1,TRANSFER,35063.63,C1364127192,35063.63,0.0,C1136419747,0.0,0.0,1,1,1,0.999971,35063.63,0.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6362610,742,TRANSFER,63416.99,C778071008,63416.99,0.0,C1812552860,0.0,0.0,1,22,0,0.999984,63416.99,0.0,0,1
6362612,743,TRANSFER,1258818.82,C1531301470,1258818.82,0.0,C1470998563,0.0,0.0,1,23,0,0.999999,1258818.82,0.0,0,1
6362614,743,TRANSFER,339682.13,C2013999242,339682.13,0.0,C1850423904,0.0,0.0,1,23,0,0.999997,339682.13,0.0,0,1
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.0,C1881841831,0.0,0.0,1,23,0,1.000000,6311409.28,0.0,0,1


# 2. Encoding Categorical Feature

In [27]:
dummies = pd.get_dummies(df['type']).astype(int)
dummies.tail()

,PAYMENT,TRANSFER
6362610,0,1
6362612,0,1
6362614,0,1
6362616,0,1
6362618,0,1


In [28]:
df = pd.get_dummies(df, columns=['type'], drop_first=True)

In [29]:
df.head()

,step,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,hour,is_night,amount_ratio,sender_balance_change,receiver_balance_change,orig_balance_zero,dest_balance_zero,type_TRANSFER
0,1,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,1,1,0.057834,9839.64,0.0,0,1,0
1,1,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,1,1,0.087731,1864.28,0.0,0,1,0
2,1,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,1,1,0.994505,181.00,0.0,0,1,1
4,1,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,1,1,0.280788,11668.14,0.0,0,1,0
5,1,7817.71,C90045638,53860.0,46042.29,M573487274,0.0,0.0,0,1,1,0.145146,7817.71,0.0,0,1,0


In [30]:
df['type_TRANSFER'] = df['type_TRANSFER'].astype(int)
df.head()

,step,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,hour,is_night,amount_ratio,sender_balance_change,receiver_balance_change,orig_balance_zero,dest_balance_zero,type_TRANSFER
0,1,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,1,1,0.057834,9839.64,0.0,0,1,0
1,1,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,1,1,0.087731,1864.28,0.0,0,1,0
2,1,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,1,1,0.994505,181.00,0.0,0,1,1
4,1,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,1,1,0.280788,11668.14,0.0,0,1,0
5,1,7817.71,C90045638,53860.0,46042.29,M573487274,0.0,0.0,0,1,1,0.145146,7817.71,0.0,0,1,0


# 3. Dropping Irrelevant Columns

In [31]:
df.drop(['nameOrig', 'nameDest'], axis=1, inplace=True)

In [32]:
df.shape

(2684404, 15)

In [33]:
df.sample(10)

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,hour,is_night,amount_ratio,sender_balance_change,receiver_balance_change,orig_balance_zero,dest_balance_zero,type_TRANSFER
6193745,571,151930.20,0.00,0.00,286749.65,438679.85,0,19,0,151930.200000,0.00,151930.20,1,0,1
3187332,240,89141.48,37095.00,0.00,72461.96,161603.44,0,0,1,2.402994,37095.00,89141.48,0,0,1
4034457,299,72191.26,8062.00,0.00,0.00,0.00,0,11,0,8.953399,8062.00,0.00,0,1,0
3786903,280,4324.88,11746.00,7421.12,0.00,0.00,0,16,0,0.368169,4324.88,0.00,0,1,0
880186,42,148904.79,0.00,0.00,505796.77,654701.56,0,18,0,148904.790000,0.00,148904.79,1,0,1
3948352,287,3812.80,184.00,0.00,0.00,0.00,0,23,0,20.609730,184.00,0.00,0,1,0
6139777,544,5361.87,8205.49,2843.62,0.00,0.00,0,16,0,0.653369,5361.87,0.00,0,1,0
5439801,378,29190.04,11439.00,0.00,0.00,0.00,0,18,0,2.551577,11439.00,0.00,0,1,0
5885653,403,11268.29,0.00,0.00,0.00,0.00,0,19,0,11268.290000,0.00,0.00,1,1,0
628369,34,71363.85,0.00,0.00,313124.44,693148.73,0,10,0,71363.850000,0.00,380024.29,1,0,1


# Independent and dependent feature

In [34]:
df.drop(columns=['step'], inplace=True)

In [35]:
x = df.drop('isFraud', axis=1)
y = df['isFraud']

In [36]:
x

,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,hour,is_night,amount_ratio,sender_balance_change,receiver_balance_change,orig_balance_zero,dest_balance_zero,type_TRANSFER
0,9839.64,170136.00,160296.36,0.0,0.0,1,1,0.057834,9839.64,0.0,0,1,0
1,1864.28,21249.00,19384.72,0.0,0.0,1,1,0.087731,1864.28,0.0,0,1,0
2,181.00,181.00,0.00,0.0,0.0,1,1,0.994505,181.00,0.0,0,1,1
4,11668.14,41554.00,29885.86,0.0,0.0,1,1,0.280788,11668.14,0.0,0,1,0
5,7817.71,53860.00,46042.29,0.0,0.0,1,1,0.145146,7817.71,0.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6362610,63416.99,63416.99,0.00,0.0,0.0,22,0,0.999984,63416.99,0.0,0,1,1
6362612,1258818.82,1258818.82,0.00,0.0,0.0,23,0,0.999999,1258818.82,0.0,0,1,1
6362614,339682.13,339682.13,0.00,0.0,0.0,23,0,0.999997,339682.13,0.0,0,1,1
6362616,6311409.28,6311409.28,0.00,0.0,0.0,23,0,1.000000,6311409.28,0.0,0,1,1


In [37]:
y

0          0
1          0
2          1
4          0
5          0
          ..
6362610    1
6362612    1
6362614    1
6362616    1
6362618    1
Name: isFraud, Length: 2684404, dtype: int64

# Train - Test Split

In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state= 42, shuffle=True)

In [39]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((2013303, 13), (671101, 13), (2013303,), (671101,))

# Model Training

# Logistic Regression

In [40]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

import joblib
joblib.dump(scaler, "scaler_latest.pkl")

['scaler_latest.pkl']

In [41]:
x_train_scaled

array([[ 0.02550296, -0.23807271, -0.23316813, ...,  1.24078014,
        -2.17655541,  2.00964526],
       [-0.19588309, -0.2166288 , -0.23316813, ..., -0.80594456,
         0.45944155, -0.49760026],
       [-0.20482755, -0.23807271, -0.23316813, ...,  1.24078014,
         0.45944155, -0.49760026],
       ...,
       [ 0.08556266, -0.15567094, -0.23316813, ..., -0.80594456,
        -2.17655541,  2.00964526],
       [-0.18880476, -0.19843462, -0.23316813, ..., -0.80594456,
         0.45944155, -0.49760026],
       [ 0.84042163, -0.19862663, -0.23316813, ..., -0.80594456,
        -2.17655541,  2.00964526]])

In [42]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=10000)

In [43]:
lr.fit(x_train_scaled, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,10000
,multi_class,'deprecated'


In [44]:
y_pred1 = lr.predict(x_test_scaled)
y_pred1

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Check the classification report of the logistic regression model

In [45]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

acc_score = accuracy_score(y_test, y_pred1)
print(f"accuracy score : {acc_score} ")
print()
print("Confusion matrix :")
print(confusion_matrix(y_test, y_pred1))
print()
print("Classification Report :")
print(classification_report(y_test, y_pred1))

accuracy score : 0.9995946958803519 

Confusion matrix :
[[670046      8]
 [   264    783]]

Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    670054
           1       0.99      0.75      0.85      1047

    accuracy                           1.00    671101
   macro avg       0.99      0.87      0.93    671101
weighted avg       1.00      1.00      1.00    671101



# Decision Tree Classifier

In [46]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
dt = DecisionTreeClassifier(max_depth=5, class_weight={0 : 1, 1 : 10 })

In [48]:
dt.fit(x_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,5
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,"{0: 1, 1: 10}"


# Visualize the Decision Tree

In [49]:
dt.get_depth()

5

In [50]:
y_pred = dt.predict(x_test)

In [51]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Check the classification report of the model

In [52]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [53]:
acc_score = accuracy_score(y_test, y_pred)
print(f"accuracy score : {acc_score} ")
print()
print("Confusion matrix :")
print(confusion_matrix(y_test, y_pred))
print()
print("Classification Report :")
print(classification_report(y_test, y_pred))

accuracy score : 0.9999463568076936 

Confusion matrix :
[[670022     32]
 [     4   1043]]

Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    670054
           1       0.97      1.00      0.98      1047

    accuracy                           1.00    671101
   macro avg       0.99      1.00      0.99    671101
weighted avg       1.00      1.00      1.00    671101



# Typing Random Forest since DecisionTreeClassifier with accuracy 99.99% seems to be overfitting

In [54]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100,class_weight={0: 1, 1: 10}, random_state=42)

In [55]:
rf_model.fit(x_train, y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [56]:
Y_pred = rf_model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# accuracy of this model along with classification report

In [57]:
acc_score = accuracy_score(y_test, y_pred)*100
print(f"accuracy score : {acc_score} %")
print()
print("Confusion matrix :")
print(confusion_matrix(y_test, y_pred))
print()
print("Classification Report :")
print(classification_report(y_test, y_pred))

accuracy score : 99.99463568076936 %

Confusion matrix :
[[670022     32]
 [     4   1043]]

Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    670054
           1       0.97      1.00      0.98      1047

    accuracy                           1.00    671101
   macro avg       0.99      1.00      0.99    671101
weighted avg       1.00      1.00      1.00    671101



In [58]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
import joblib

pipe = Pipeline([
    ("Scaler", StandardScaler()),
    ("model", RandomForestClassifier(n_estimators = 100, class_weight={0: 1, 1: 10}, random_state =42))
])

pipe.fit(x_train, y_train)

#Evaluate
pred_test = pipe.predict(x_test)
print(classification_report(y_test, pred_test))

# save model
joblib.dump(pipe, "fraud_pipeline.pkl")
print("Pipeline saved successfully!")

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    670054
           1       1.00      1.00      1.00      1047

    accuracy                           1.00    671101
   macro avg       1.00      1.00      1.00    671101
weighted avg       1.00      1.00      1.00    671101

Pipeline saved successfully!


In [63]:
import joblib

pipe_loaded = joblib.load("fraud_pipeline.pkl")
y_pred_loaded = pipe_loaded.predict(x_test)
print(classification_report(y_test, y_pred_loaded))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    670054
           1       1.00      1.00      1.00      1047

    accuracy                           1.00    671101
   macro avg       1.00      1.00      1.00    671101
weighted avg       1.00      1.00      1.00    671101

